site_name: FakePlayerMaker-Wiki
site_url: https://wiki.hiworldmc.com/FakePlayerMaker/
plugins:
  - search
theme:
  name: material
  features:
    - navigation.instant
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  icon:
    repo: "fontawesome/brands/github"
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 简体中文
      link: /zh/index.md
      lang: zh
repo_url: https://github.com/LinsMinecraftStudio/FakePlayerMaker-Wiki   
repo_name: LinsMinecraftStudio/FakePlayerMaker-Wiki
nav:
  - Discord: "https://discord.gg/W36MJhBtGy"