site_name: FakePlayerMaker-Wiki
site_url: https://wiki.hiworldmc.com/FakePlayerMaker/
plugins:
  - search
theme:
  name: material
  features:
    - navigation.instant
    - search.suggest
    - search.highlight
extra:
  alternate:
    - name: English
      link: /FakePlayerMaker-Wiki/
      lang: en
    - name: 简体中文
      link: /FakePlayerMaker-Wiki/zh/index.md
      lang: zh
repo_url: https://github.com/LinsMinecraftStudio/FakePlayerMaker-Wiki   
repo_name: LinsMinecraftStudio/FakePlayerMaker-Wiki