site_name: FakePlayerMaker-Wiki
site_url: https://lms.hiworldmc.com/FakePlayerMaker-Wiki/
plugins:
  - search
theme:
  name: material
  features:
    - navigation.instant
    - search.suggest
    - search.highlight
extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: 简体中文
      link: /zh/
      lang: zh
repo_url: https://github.com/LinsMinecraftStudio/FakePlayerMaker-Wiki   